application: cookpad-popentry
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /get_hateb_entry
  script: get_hateb_entry.py
  login: admin
- url: /get_cookpad_recipe
  script: get_cookpad_recipe.py
  login: admin
- url: /.*
  script: mainpage.py

builtins:
- datastore_admin: on